---
abstract: "Perl IDE backend with Emacs frontend\r"
author:
  - 'Johan Lindstrom <johanl@cpan.org>'
build_requires:
  Class::MethodMaker: 0
  Exception::Class: 0
  File::Spec: 0
  File::Temp: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-PerlySense
requires:
  App::Ack: 0
  Cache::Cache: 0
  Cache::FileCache: 0
  Carp: 0
  Data::Dumper: 0
  Exporter: 0
  File::Basename: 0
  File::Find: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  File::chdir: 0
  Getopt::Long: 0
  Graph::Easy: 0
  HTTP::Date: 0
  IO::String: 0
  List::MoreUtils: 0
  List::Util: 0
  Module::Pluggable: 3.5
  POSIX: 0
  PPI: 1.003
  PPI::Document: 0
  PPI::Dumper: 0
  Path::Class: 0.11
  Perl::Critic: 1.105
  Perl::Tidy: 0
  Pod::Text: 0
  Pod::Usage: 0
  Spiffy: 0
  Storable: 0
  Text::Table: 0
  Time::HiRes: 0
  YAML::Tiny: 0
version: 0.0190
